### ISSUE TITLE
Generate report doesn't work if the game is running

### ISSUE THREAD

**Issue by Moneyl** [rfg-modding/SyncFaction#6]
Got these exceptions since the game had a lock on some files:
```
System.IO.IOException: The process cannot access the file 'D:\GOG\Games\Red Faction Guerrilla Re-Mars-tered\binkw32.dll' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileInfo.Open(FileMode mode)
   at System.IO.Abstractions.FileInfoWrapper.Open(FileMode mode)
   at SyncFaction.Core.Services.Files.FileChecker.ComputeHash(IFileInfo file, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileChecker.cs:line 97
   at SyncFaction.Core.Services.Files.FileManager.<>c__DisplayClass9_0.<<GenerateFileReport>g__ReportFile|0>d.MoveNext() in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileManager.cs:line 266
--- End of stack trace from previous location ---
   at SyncFaction.Core.Services.ParallelHelper.<>c__DisplayClass4_0!1.<<Execute>b__0>d.MoveNext() in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\ParallelHelper.cs:line 34
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50!1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SyncFaction.Core.Services.ParallelHelper.Execute[T](IReadOnlyList!1 data, Func!4 body, Int32 threadCount, TimeSpan reportPeriod, String operation, String unit, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\ParallelHelper.cs:line 41
   at SyncFaction.Core.Services.Files.FileManager.GenerateFileReport(IAppStorage storage, Int32 threadCount, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileManager.cs:line 249
   at SyncFaction.Services.UiCommands.GenerateReport(ViewModel viewModel, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction\Services\UiCommands.cs:line 513
   ```

**Comment by Moneyl** [comment]
A similar thing is happening with SyncFaction.exe when it's in the games root folder or data folder
```
System.IO.IOException: The process cannot access the file 'D:\GOG\Games\Red Faction Guerrilla Re-Mars-tered\data\SyncFaction.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Abstractions.FileInfoWrapper.Open(FileMode mode)
   at SyncFaction.Core.Services.Files.FileChecker.ComputeHash(IFileInfo file, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileChecker.cs:line 97
   at SyncFaction.Core.Services.Files.FileManager.<>c__DisplayClass9_0.<<GenerateFileReport>g__ReportFile|0>d.MoveNext() in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileManager.cs:line 266
--- End of stack trace from previous location ---
   at SyncFaction.Core.Services.ParallelHelper.<>c__DisplayClass4_0!1.<<Execute>b__0>d.MoveNext() in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\ParallelHelper.cs:line 34
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50!1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SyncFaction.Core.Services.ParallelHelper.Execute[T](IReadOnlyList!1 data, Func!4 body, Int32 threadCount, TimeSpan reportPeriod, String operation, String unit, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\ParallelHelper.cs:line 41
   at SyncFaction.Core.Services.Files.FileManager.GenerateFileReport(IAppStorage storage, Int32 threadCount, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction.Core\Services\Files\FileManager.cs:line 249
   at SyncFaction.Services.UiCommands.GenerateReport(ViewModel viewModel, CancellationToken token) in C:\vault\rfg\SyncFaction\src\SyncFaction\Services\UiCommands.cs:line 513
```

**Comment by Rast1234** [comment]
true. game holds a lock on files, and SF tries to read and hash everything. i feel it's better to fail report generation rather than make a report with missing information, what do you think?

**Comment by Rast1234** [comment]
btw if you want to get SF logs quickly there is a button for that which skips hash gen
